require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::ShowsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Show. As you add validations to Admin::Show, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ShowsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_shows as @admin_shows" do
      show = Admin::Show.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:admin_shows)).to eq([show])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_show as @admin_show" do
      show = Admin::Show.create! valid_attributes
      get :show, {:id => show.to_param}, valid_session
      expect(assigns(:admin_show)).to eq(show)
    end
  end

  describe "GET new" do
    it "assigns a new admin_show as @admin_show" do
      get :new, {}, valid_session
      expect(assigns(:admin_show)).to be_a_new(Admin::Show)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_show as @admin_show" do
      show = Admin::Show.create! valid_attributes
      get :edit, {:id => show.to_param}, valid_session
      expect(assigns(:admin_show)).to eq(show)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Show" do
        expect {
          post :create, {:admin_show => valid_attributes}, valid_session
        }.to change(Admin::Show, :count).by(1)
      end

      it "assigns a newly created admin_show as @admin_show" do
        post :create, {:admin_show => valid_attributes}, valid_session
        expect(assigns(:admin_show)).to be_a(Admin::Show)
        expect(assigns(:admin_show)).to be_persisted
      end

      it "redirects to the created admin_show" do
        post :create, {:admin_show => valid_attributes}, valid_session
        expect(response).to redirect_to(Admin::Show.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_show as @admin_show" do
        post :create, {:admin_show => invalid_attributes}, valid_session
        expect(assigns(:admin_show)).to be_a_new(Admin::Show)
      end

      it "re-renders the 'new' template" do
        post :create, {:admin_show => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_show" do
        show = Admin::Show.create! valid_attributes
        put :update, {:id => show.to_param, :admin_show => new_attributes}, valid_session
        show.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested admin_show as @admin_show" do
        show = Admin::Show.create! valid_attributes
        put :update, {:id => show.to_param, :admin_show => valid_attributes}, valid_session
        expect(assigns(:admin_show)).to eq(show)
      end

      it "redirects to the admin_show" do
        show = Admin::Show.create! valid_attributes
        put :update, {:id => show.to_param, :admin_show => valid_attributes}, valid_session
        expect(response).to redirect_to(show)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_show as @admin_show" do
        show = Admin::Show.create! valid_attributes
        put :update, {:id => show.to_param, :admin_show => invalid_attributes}, valid_session
        expect(assigns(:admin_show)).to eq(show)
      end

      it "re-renders the 'edit' template" do
        show = Admin::Show.create! valid_attributes
        put :update, {:id => show.to_param, :admin_show => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_show" do
      show = Admin::Show.create! valid_attributes
      expect {
        delete :destroy, {:id => show.to_param}, valid_session
      }.to change(Admin::Show, :count).by(-1)
    end

    it "redirects to the admin_shows list" do
      show = Admin::Show.create! valid_attributes
      delete :destroy, {:id => show.to_param}, valid_session
      expect(response).to redirect_to(admin_shows_url)
    end
  end

end
