require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Website::StagesController, :type => :controller do

  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all website_stages as @clapme_stages" do
      stage = Clapme::Stage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:clapme_stages)).to eq([stage])
    end
  end

  describe "GET show" do
    it "assigns the requested website_stage as @clapme_stage" do
      stage = Clapme::Stage.create! valid_attributes
      get :show, {:id => stage.to_param}, valid_session
      expect(assigns(:clapme_stage)).to eq(stage)
    end
  end

  describe "GET new" do
    it "assigns a new website_stage as @clapme_stage" do
      get :new, {}, valid_session
      expect(assigns(:clapme_stage)).to be_a_new(Clapme::Stage)
    end
  end

  describe "GET edit" do
    it "assigns the requested website_stage as @clapme_stage" do
      stage = Clapme::Stage.create! valid_attributes
      get :edit, {:id => stage.to_param}, valid_session
      expect(assigns(:clapme_stage)).to eq(stage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Website::Stage" do
        expect {
          post :create, {:stage => valid_attributes}, valid_session
        }.to change(Clapme::Stage, :count).by(1)
      end

      it "assigns a newly created website_stage as @clapme_stage" do
        post :create, {:stage => valid_attributes}, valid_session
        expect(assigns(:clapme_stage)).to be_a(Clapme::Stage)
        expect(assigns(:clapme_stage)).to be_persisted
      end

      it "redirects to the created website_stage" do
        post :create, {:stage => valid_attributes}, valid_session
        expect(response).to redirect_to(Clapme::Stage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved website_stage as @clapme_stage" do
        post :create, {:stage => invalid_attributes}, valid_session
        expect(assigns(:clapme_stage)).to be_a_new(Clapme::Stage)
      end

      it "re-renders the 'new' template" do
        post :create, {:stage => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested website_stage" do
        stage = Clapme::Stage.create! valid_attributes
        put :update, {:id => stage.to_param, :stage => new_attributes}, valid_session
        stage.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested website_stage as @clapme_stage" do
        stage = Clapme::Stage.create! valid_attributes
        put :update, {:id => stage.to_param, :stage => valid_attributes}, valid_session
        expect(assigns(:clapme_stage)).to eq(stage)
      end

      it "redirects to the website_stage" do
        stage = Clapme::Stage.create! valid_attributes
        put :update, {:id => stage.to_param, :stage => valid_attributes}, valid_session
        expect(response).to redirect_to(stage)
      end
    end

    describe "with invalid params" do
      it "assigns the website_stage as @clapme_stage" do
        stage = Clapme::Stage.create! valid_attributes
        put :update, {:id => stage.to_param, :stage => invalid_attributes}, valid_session
        expect(assigns(:clapme_stage)).to eq(stage)
      end

      it "re-renders the 'edit' template" do
        stage = Clapme::Stage.create! valid_attributes
        put :update, {:id => stage.to_param, :stage => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested website_stage" do
      stage = Clapme::Stage.create! valid_attributes
      expect {
        delete :destroy, {:id => stage.to_param}, valid_session
      }.to change(Clapme::Stage, :count).by(-1)
    end

    it "redirects to the website_stages list" do
      stage = Clapme::Stage.create! valid_attributes
      delete :destroy, {:id => stage.to_param}, valid_session
      expect(response).to redirect_to(website_stages_url)
    end
  end

end
