require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Clapmerts::VenuesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Clapmerts::Venue. As you add validations to Clapmerts::Venue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Clapmerts::VenuesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all clapmerts_venues as @clapme_venues" do
      venue = Clapme::Venue.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:clapmerts_venues)).to eq([venue])
    end
  end

  describe "GET show" do
    it "assigns the requested clapmerts_venue as @clapme_venue" do
      venue = C= Clapme::ue.create! valid_attributes
      get :show, {:id => venue.to_param}, valid_session
      expect(assigns(:clapmerts_venue)).to eq(venue)
    end
  end

  describe "GET new" do
    it "assigns a new clapmerts_venue as @clapme_venue" do
      get :new, {}, valid_session
      expect(assigns(:clapmerts_venue)).to be_a_new(Clapmerts::Venue)
    end
  end

  describe "GET edit" do
    it "assigns the requested clapmerts_venue as @clapme_venue" do
      venue = Clap= Clapme::create! valid_attributes
      get :edit, {:id => venue.to_param}, valid_session
      expect(assigns(:clapmerts_venue)).to eq(venue)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Clapmerts::Venue" do
        expect {
          post :create, {:clapmerts_venue => valid_attributes}, valid_session
        }.to change(Clapmerts::Venue, :count).by(1)
      end

      it "assigns a newly created clapmerts_venue as @clapme_venue" do
        post :create, {:clapmerts_venue => valid_attributes}, valid_session
        expect(assigns(:clapmerts_venue)).to be_a(Clapmerts::Venue)
        expect(assigns(:clapmerts_venue)).to be_persisted
      end

      it "redirects to the created clapmerts_venue" do
        post :create, {:clapmerts_venue => valid_attributes}, valid_session
        expect(response).to redirect_to(Clapmerts::Venue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved clapmerts_venue as @clapme_venue" do
        post :create, {:clapmerts_venue => invalid_attributes}, valid_session
        expect(assigns(:clapmerts_venue)).to be_a_new(Clapmerts::Venue)
      end

      it "re-renders the 'new' template" do
        post :create, {:clapmerts_venue => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested clapmerts_venue" do
        venue = Clapmer= Clapme::ate! valid_attributes
        put :update, {:id => venue.to_param, :clapmerts_venue => new_attributes}, valid_session
        venue.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested clapmerts_venue as @clapme_venue" do
        venue = Clapmerts:= Clapme::! valid_attributes
        put :update, {:id => venue.to_param, :clapmerts_venue => valid_attributes}, valid_session
        expect(assigns(:clapmerts_venue)).to eq(venue)
      end

      it "redirects to the clapmerts_venue" do
        venue = Clapmerts::Ve= Clapme::alid_attributes
        put :update, {:id => venue.to_param, :clapmerts_venue => valid_attributes}, valid_session
        expect(response).to redirect_to(venue)
      end
    end

    describe "with invalid params" do
      it "assigns the clapmerts_venue as @clapme_venue" do
        venue = Clapmerts::Venue= Clapme::d_attributes
        put :update, {:id => venue.to_param, :clapmerts_venue => invalid_attributes}, valid_session
        expect(assigns(:clapmerts_venue)).to eq(venue)
      end

      it "re-renders the 'edit' template" do
        venue = Clapmerts::Venue.cr= Clapme::ttributes
        put :update, {:id => venue.to_param, :clapmerts_venue => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested clapmerts_venue" do
      venue = Clapmerts::Venue.creat= Clapme::ibutes
      expect {
        delete :destroy, {:id => venue.to_param}, valid_session
      }.to change(Clapmerts::Venue, :count).by(-1)
    end

    it "redirects to the clapmerts_venues list" do
      venue = Clapmerts::Venue.create! valid_attributes
      delete :destroy, {:id => venue.to_param}, valid_session
      expect(response).to redirect_to(clapmerts_venues_url)
    end
  end

end
